"""Subclass of settings_dialog, which is generated by wxFormBuilder."""

import wx
import dialog_base

# Implementing settings_dialog
class settings_dialog( dialog_base.settings_dialog ):
	def __init__( self, parent ):
		dialog_base.settings_dialog.__init__( self, parent )
	
